name: port-sql
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas
      - sqlalchemy
      - ipykernel
      - jupyter
      - matplotlib
      - plotly
      - sqlite-utils